services:
  task-manager-db:
    image: mysql:8.0
    container_name: task-manager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
      interval: 2s

  task-manager-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: task-manager-backend:${BACKEND_VERSION:-latest}
    container_name: task-manager-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      task-manager-db:
        condition: service_healthy

  task-manager-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: task-manager-frontend:${FRONTEND_VERSION:-latest}
    container_name: task-manager-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - task-manager-backend

volumes:
  mysql_data:
